version: '3'
services:
  rec-server:
    image: rec-server
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "5000:5000"
    depends_on:
       - postgres-db
    volumes:
      - .:/app
  postgres-db:
    image: "postgres-db"
    environment:
       POSTGRES_PASSWORD: postgres